### ISSUE TITLE
Resource Pack Not Loading / No connected textures

### ISSUE THREAD

**Issue by WiseNoobCrusher** [HarvelsX/Continuity#1]
This applies to the 1.19/dev

Everytime I try to apply FaithfulVenom or even Programmer Art to see if it will accept any resource pack, it wont load it.

Also, the connected textures wont connect even with the default textures.

Idk where I went wrong... :/

![image](https://user-images.githubusercontent.com/33038133/172520295-5c7b228b-e817-422e-bf81-9dee1b314307.png)

**Comment by HarvelsX** [comment]
What modifications do you use besides Continuity?

**Comment by WiseNoobCrusher** [comment]
These are the mods I use
![image](https://user-images.githubusercontent.com/33038133/172521066-1e2c6df9-c360-4d93-b052-a22330e52aa3.png)

**Comment by HarvelsX** [comment]
It seems you need Indium, by default Sodium has no Fabric API.
Try using my fork Plumbum, the Indium fork (https://github.com/HarvelsX/Plumbum):
[plumbum-0.1.0-dev.b3729f7+mc1.19-dirty.jar.zip](https://github.com/HarvelsX/Continuity/files/8857932/plumbum-0.1.0-dev.b3729f7%2Bmc1.19-dirty.jar.zip)

**Comment by WiseNoobCrusher** [comment]
> It seems you need Indium, by default Sodium has no Fabric API. Try using my fork Plumbum, the Indium fork (https://github.com/HarvelsX/Plumbum): [plumbum-0.1.0-dev.b3729f7+mc1.19-dirty.jar.zip](https://github.com/HarvelsX/Continuity/files/8857932/plumbum-0.1.0-dev.b3729f7%2Bmc1.19-dirty.jar.zip)

That did it, it works now, thank you so much :)

**Comment by HarvelsX** [comment]
No problem. Have a good game!

**Comment by WiseNoobCrusher** [comment]
> It seems you need Indium, by default Sodium has no Fabric API. Try using my fork Plumbum, the Indium fork (https://github.com/HarvelsX/Plumbum): [plumbum-0.1.0-dev.b3729f7+mc1.19-dirty.jar.zip](https://github.com/HarvelsX/Continuity/files/8857932/plumbum-0.1.0-dev.b3729f7%2Bmc1.19-dirty.jar.zip)

The plumbum mod u gave me, messes up the Trident texture (Item form)
![image](https://user-images.githubusercontent.com/33038133/172698319-198945c4-357e-4f2e-a7fe-129710fbdf1c.png)
Used default texture to prove it does it without FaithfulVenom.

EDIT: The reason I put this here, is cause there is no issues tab on your fork of Plumbum.

**Comment by HarvelsX** [comment]
Thanks for letting me know, I'll take a look later, but it's not critical, is it?

**Comment by WiseNoobCrusher** [comment]
> Thanks for letting me know, I'll take a look later, but it's not critical, is it?

No, it doesn't inhibit the trident from working or crash the game. Just making you aware of this issue.

**Comment by HarvelsX** [comment]
@WiseNoobCrusher, okay, I think I fixed that, so here you go:
[plumbum-0.1.0-dev.dd17cd2+mc1.19.jar.zip](https://github.com/HarvelsX/Continuity/files/8872927/plumbum-0.1.0-dev.dd17cd2%2Bmc1.19.jar.zip)

**Comment by WiseNoobCrusher** [comment]
> Owner

It is fixed, thank you so much :)
